### ISSUE TITLE
Setup meta:og-image with solid hb5 logo

### ISSUE THREAD

**Issue by shrop** [hb5co/hb5co-drupal#21]
shrop [8:31 AM] 
@bayo: is there a way to have the image pulled form our site not use the one in the header or maybe make the one in the headers solid? see the reddit post https://www.reddit.com/r/Meteor/

reddit
/r/Meteor: a reddit for discussion & news about Meteor.JS
**A reddit for discussion and news about Meteor.JS** Meteor is a set of new technologies for building top-quality web apps in a fraction of the...

bayo [8:32 AM] 
yea, I think it’s just pulling the first image it finds

shrop [8:32 AM] 
cool

bayo [8:32 AM] 
I can set it up to use meta:og-image

​[8:33] 
hb5.co

shrop [8:33 AM] 
^^ i was thinking there was a standard for that

​[8:33] 
good to know..

​[8:33] 
want me to make an issue on github?

bayo [8:34 AM] 
yes please

shrop [8:34 AM] 
will do!

**Comment by bfodeke** [comment]
@shrop the meta tag setup is done via the metatag module and I'm not sure if that is exportable to a feature. Should I update the live site to point at a file that I drop in /sites/default/files?

**Comment by shrop** [comment]
live site edit works for me!

**Comment by bfodeke** [comment]
Just saw that it IS infact exportable, so I'll create a feature :smile:

**Comment by shrop** [comment]
Cool!

**Comment by shrop** [comment]
@bayo I enabled the feature on http://staging.hb5.co. Can you upload cover.jpg?

Also, i missed something in CR. Can we make a folder sites/all/modules/features and name the feature something like hb5_metatag? I think that will be better org.

**Comment by shrop** [comment]
@bfodeke ping

**Comment by shrop** [comment]
@bfodeke ping
